(define InvertCaptcha
  (lambda (captcha)
    (sommaStringhe (StringCaptcha_parte2 captcha (string-append captcha captcha)))
    ))
(define StringCaptcha_parte2
  (lambda (captcha 2captcha) ;il primo rimane fisso, il secondo deve variare, il terzo è il doppio
    (let ((i (/ (string-length captcha) 2)))
      (let ((x (substring 2captcha 0 1)))
        (let ((k (substring 2captcha 1)))
          (cond ((= (- (string-length 2captcha) 1) (string-length captcha))
                 (if (string=? x (substring 2captcha i (+ i 1)))
                     (string-append x "")
                     ""))
                ((string=? x (substring 2captcha i (+ i 1))) (string-append x (StringCaptcha_parte2 captcha k)))
                (else (StringCaptcha_parte2 captcha k))
                )
          )))
    ))
(define sommaStringhe
  (lambda (str)
    (if (> (string-length str) 0)
        (+ (Calcolo (substring str 0 1)) (sommaStringhe (substring str 1)))
        0)
    ))
(define Calcolo
  (lambda (captcha)
    (let ((x (substring captcha 0 1)))
      (cond ((string=? "1" x) 1)
            ((string=? "2" x) 2)
            ((string=? "3" x) 3)
            ((string=? "4" x) 4)
            ((string=? "5" x) 5)
            ((string=? "6" x) 6)
            ((string=? "7" x) 7)
            ((string=? "8" x) 8)
            ((string=? "9" x) 9)
            ((string=? ""  x) 0))
      )
    ))
